export const surpriseMePrompts = [
    'an armchair in the shape of an avocado',
    'a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers',
    'teddy bears shopping for groceries in Japan, ukiyo-e',
    'an oil painting by Matisse of a humanoid robot playing chess',
    'panda mad scientist mixing sparkling chemicals, digital art',
    "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
    '3D render of a cute tropical fish in an aquarium on a dark blue background, digital art',
    'an astronaut lounging in a tropical resort in space, vaporwave',
    'an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background',
    'a stained glass window depicting a hamburger and french fries',
    'a pencil and watercolor drawing of a bright city in the future with flying cars',
    'a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art',
    'a fortune-telling shiba inu reading your fate in a giant hamburger, digital art',
    '"a sea otter with a pearl earring" by Johannes Vermeer',
    'an oil pastel drawing of an annoyed cat in a spaceship',
    'a painting of a fox in the style of Starry Night',
    'a bowl of soup that looks like a monster, knitted out of wool',
    'A plush toy robot sitting against a yellow wall',
    'A synthwave style sunset above the reflecting water of the sea, digital art',
    'Two futuristic towers with a skybridge covered in lush foliage, digital art',
    'A 3D render of a rainbow colored hot air balloon flying above a reflective lake',
    'A comic book cover of a superhero wearing headphones',
    'A centered explosion of colorful powder on a black background',
    'A photo of a Samoyed dog with its tongue out hugging a white Siamese cat',
    'A photo of a white fur monster standing in a purple room',
    "A photo of Michelangelo's sculpture of David wearing headphones djing",
    'A Samurai riding a Horse on Mars, lomography.',
    'A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography',
    'A realistic photograph of a young woman with blue eyes and blonde hair',
    'A man standing in front of a stargate to another dimension',
    'Spongebob Squarepants in the Blair Witch Project',
    'A velociraptor working at a hotdog stand, lomography',
    'A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens',
    'A BBQ that is alive, in the style of a Pixar animated movie',
    'A futuristic cyborg dance club, neon lights',
    'The long-lost Star Wars 1990 Japanese Anime',
    'A hamburger in the shape of a Rubik’s cube, professional food photography',
    'A Synthwave Hedgehog, Blade Runner Cyberpunk',
    'An astronaut encountering an alien life form on a distant planet, photography',
    'A Dinosaur exploring Cape Town, photography',
    'A Man falling in Love with his Computer, digital art',
    'A photograph of a cyborg exploring Tokyo at night, lomography',
    'Dracula walking down the street of New York City in the 1920s, black and white photography',
    'Synthwave aeroplane',
    'A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm',
    'A Space Shuttle flying above Cape Town, digital art',
    'A neon-lit cityscape with flying cars zooming between towering skyscrapers, cyberpunk style.',
    'A dragon made of glass flying through a misty forest, digital art.',
    'A 3D render of a cozy treehouse nestled inside a giant sunflower.',
    'A futuristic robot chef preparing sushi in a Tokyo street market.',
    'A detailed charcoal sketch of a knight riding a flaming horse through a stormy battlefield.',
    'A steampunk-style airship flying over a Victorian-era London, fog rolling through the streets.',
    'A group of penguins surfing on colorful surfboards under a sunset sky, digital art.',
    'A majestic lion with a mane made of stars, floating through outer space.',
    'An ancient stone temple built on the back of a giant turtle swimming in the ocean.',
    'A futuristic skyscraper covered in plants and greenery, with flying drones in the background.',
    'A 3D render of a jellyfish swimming through a neon-lit underwater city.',
    'A whimsical scene of giraffes riding bicycles through a field of colorful flowers.',
    'A robot orchestra performing in front of a massive audience of glowing alien creatures.',
    'A polar bear DJing at a snowy outdoor music festival with aurora borealis in the background.',
    'A magical forest where trees are made of crystal and glowing mushrooms line the path.',
    'A black and white photograph of a samurai standing on a beach at sunrise, waves crashing behind.',
    'A hyper-realistic painting of a phoenix rising from the flames, feathers glowing with intense colors.',
    'A serene countryside with windmills and hot air balloons in a clear blue sky, digital art.',
    'A futuristic city park where people walk alongside robotic dogs and drones deliver coffee.',
    'A retro 80s-style diner with neon signs, chrome finishes, and a robot serving milkshakes.',
    'A lush tropical island floating in the sky, with waterfalls cascading off the edges.',
    'A young astronaut exploring an alien desert landscape, with giant planets visible in the sky.',
    'A steampunk clock tower with intricate gears and a glowing blue orb in the center, digital art.',
    'A group of pandas playing in a futuristic arcade with neon lights and holographic games.',
    'A surreal landscape where giant ice cream cones grow like trees in a candy land.',
    'A massive futuristic ship docked in an underwater harbor, surrounded by glowing sea creatures.',
    'A futuristic train speeding through a snow-covered mountain range at sunset, digital art.',
    'A giant robot guarding an ancient temple in the middle of a desert, digital art.',
    'A surreal cityscape where buildings are made of books and streets are lined with typewriters.',
    'A 3D render of a spacecraft landing on a planet with purple skies and alien flora.',
];